#Fri Aug 25 11:03:55 GMT 2023
micronaut:
  application:
    name: 'odabagen'

obsidian:
  db-file-name: 'Project_Files.md'
  database:
    name: database
    description: description
    folder:
      options: [ ]
    type:
      options:
        - { label: "ARCHIVE", value: "archive", color: "hsl(231, 95%, 90%)" }
    event:
      options:
        - { label: "maydan", value: "maydan", color: "hsl(128, 95%, 90%)" }
        - { label: "politics", value: "politics", color: "hsl(182, 95%, 90%)" }
